// Generated by CoffeeScript 1.9.1
var addByDate, i, j, len, len1, link, links, linksOnly, lohref, newElement, pagetop, toggleLinks;

pagetop = document.getElementsByClassName('pagetop')[0];

newElement = ' | <span><a id="lohref" href="#">LinksOnly</a>';

pagetop.insertAdjacentHTML('beforeend', newElement);

lohref = document.getElementById("lohref");

links = document.querySelectorAll(".comment a:not([href^='reply?'])");

for (i = 0, len = links.length; i < len; i++) {
  link = links[i];
  link.target = "_blank";
}

lohref.innerHTML = "LinksOnly (" + links.length + ")";

links = document.querySelectorAll('.title a');

for (j = 0, len1 = links.length; j < len1; j++) {
  link = links[j];
  if (link.text !== "More") {
    link.target = "_blank";
  }
}

linksOnly = false;

toggleLinks = function() {
  var el, els, k, l, len2, len3, results, results1;
  els = document.querySelectorAll('.comment');
  if (linksOnly) {
    linksOnly = false;
    results = [];
    for (k = 0, len2 = els.length; k < len2; k++) {
      el = els[k];
      results.push(el.parentNode.parentNode.parentNode.parentNode.parentNode.parentNode.style.display = 'block');
    }
    return results;
  } else {
    linksOnly = true;
    results1 = [];
    for (l = 0, len3 = els.length; l < len3; l++) {
      el = els[l];
      if (el.querySelectorAll("a:not([href^='reply?'])").length < 1) {
        results1.push(el.parentNode.parentNode.parentNode.parentNode.parentNode.parentNode.style.display = 'none');
      } else {
        results1.push(void 0);
      }
    }
    return results1;
  }
};

lohref.addEventListener('click', toggleLinks, false);

addByDate = function() {
  var el, f, f1;
  f = document.querySelectorAll('form[action^="//hn"]');
  if (f.length === 1) {
    f1 = f[0];
    el = document.createElement("INPUT");
    el.type = "hidden";
    el.name = "sort";
    el.value = "byDate";
    return f1.appendChild(el);
  }
};

addByDate();
